---
- name: Download citus install script
  get_url: 
    url: https://install.citusdata.com/community/rpm.sh
    dest: /tmp/citus-rpm.sh
    mode: 0755

- name: yum | Setup Citus repository for {{ ansible_distribution }}
  shell: /tmp/citus-rpm.sh

- name: yum | Install Citus
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - citus_12
  register: install_postgresql
  tags: [db, postgresql]

- name:  check data directory existed or not
  stat:
    path: /var/lib/pgsql/data-12/Coordinator
  register: my_folder

- name: "echo if directory already existed"
  debug:
    msg: "the data directory is already existed"
  when: my_folder.stat.exists

- name: " Create data directory if not exists"
  file:
    path: /var/lib/pgsql/data-12/Coordinator
    state: directory
    mode: 0755
    group: postgres
    owner: postgres
  when: my_folder.stat.exists == false

- name: Initialize Postgres Instance
  shell: |
    /usr/pgsql-12/bin/initdb -D /var/lib/pgsql/data-12/Coordinator 
  register: status
  become: yes
  become_user: postgres

- name: Start Postgres Instance
  shell: |
    /usr/pgsql-12/bin/pg_ctl -D /var/lib/pgsql/data-12/Coordinator -l coordinator_logfile start
  register: status
  become: yes
  become_user: postgres

